/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.student.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.student.service.model.Student;
import com.student.service.model.StudentModel;
import com.student.service.model.StudentSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Student service. Represents a row in the &quot;STUDENT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>StudentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StudentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StudentImpl
 * @generated
 */
@JSON(strict = true)
public class StudentModelImpl
	extends BaseModelImpl<Student> implements StudentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a student model instance should use the <code>Student</code> interface instead.
	 */
	public static final String TABLE_NAME = "STUDENT";

	public static final Object[][] TABLE_COLUMNS = {
		{"STUDENTID", Types.BIGINT}, {"STUDENTNAME", Types.VARCHAR},
		{"STUDENTNICKNAME", Types.VARCHAR}, {"STUDENTMOBNO", Types.BIGINT},
		{"STUDENTGENDER", Types.BOOLEAN}, {"STUDENTAGE", Types.INTEGER},
		{"STUDENTDOB", Types.TIMESTAMP}, {"COMPANYID", Types.BIGINT},
		{"USERID", Types.BIGINT}, {"USERNAME", Types.VARCHAR},
		{"CREATEDATE", Types.TIMESTAMP}, {"MODIFIEDDATE", Types.TIMESTAMP},
		{"GROUPID", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("STUDENTID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("STUDENTNAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("STUDENTNICKNAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("STUDENTMOBNO", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("STUDENTGENDER", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("STUDENTAGE", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("STUDENTDOB", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("COMPANYID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("USERID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("USERNAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CREATEDATE", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("MODIFIEDDATE", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("GROUPID", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table STUDENT (STUDENTID LONG not null primary key,STUDENTNAME VARCHAR(75) null,STUDENTNICKNAME VARCHAR(75) null,STUDENTMOBNO LONG,STUDENTGENDER BOOLEAN,STUDENTAGE INTEGER,STUDENTDOB DATE null,COMPANYID LONG,USERID LONG,USERNAME VARCHAR(75) null,CREATEDATE DATE null,MODIFIEDDATE DATE null,GROUPID LONG)";

	public static final String TABLE_SQL_DROP = "drop table STUDENT";

	public static final String ORDER_BY_JPQL =
		" ORDER BY student.studentName ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY STUDENT.STUDENTNAME ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long STUDENTMOBNO_COLUMN_BITMASK = 1L;

	public static final long STUDENTNAME_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Student toModel(StudentSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Student model = new StudentImpl();

		model.setStudentId(soapModel.getStudentId());
		model.setStudentName(soapModel.getStudentName());
		model.setStudentNickName(soapModel.getStudentNickName());
		model.setStudentMobNo(soapModel.getStudentMobNo());
		model.setStudentGender(soapModel.isStudentGender());
		model.setStudentAge(soapModel.getStudentAge());
		model.setStudentDOB(soapModel.getStudentDOB());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setGroupId(soapModel.getGroupId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Student> toModels(StudentSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Student> models = new ArrayList<Student>(soapModels.length);

		for (StudentSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public StudentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _studentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setStudentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _studentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Student.class;
	}

	@Override
	public String getModelClassName() {
		return Student.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Student, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Student, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Student, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Student)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Student, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Student, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Student)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Student, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Student, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Student>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Student.class.getClassLoader(), Student.class, ModelWrapper.class);

		try {
			Constructor<Student> constructor =
				(Constructor<Student>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Student, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Student, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Student, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Student, Object>>();
		Map<String, BiConsumer<Student, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Student, ?>>();

		attributeGetterFunctions.put("studentId", Student::getStudentId);
		attributeSetterBiConsumers.put(
			"studentId", (BiConsumer<Student, Long>)Student::setStudentId);
		attributeGetterFunctions.put("studentName", Student::getStudentName);
		attributeSetterBiConsumers.put(
			"studentName",
			(BiConsumer<Student, String>)Student::setStudentName);
		attributeGetterFunctions.put(
			"studentNickName", Student::getStudentNickName);
		attributeSetterBiConsumers.put(
			"studentNickName",
			(BiConsumer<Student, String>)Student::setStudentNickName);
		attributeGetterFunctions.put("studentMobNo", Student::getStudentMobNo);
		attributeSetterBiConsumers.put(
			"studentMobNo",
			(BiConsumer<Student, Long>)Student::setStudentMobNo);
		attributeGetterFunctions.put(
			"studentGender", Student::getStudentGender);
		attributeSetterBiConsumers.put(
			"studentGender",
			(BiConsumer<Student, Boolean>)Student::setStudentGender);
		attributeGetterFunctions.put("studentAge", Student::getStudentAge);
		attributeSetterBiConsumers.put(
			"studentAge", (BiConsumer<Student, Integer>)Student::setStudentAge);
		attributeGetterFunctions.put("studentDOB", Student::getStudentDOB);
		attributeSetterBiConsumers.put(
			"studentDOB", (BiConsumer<Student, Date>)Student::setStudentDOB);
		attributeGetterFunctions.put("companyId", Student::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Student, Long>)Student::setCompanyId);
		attributeGetterFunctions.put("userId", Student::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Student, Long>)Student::setUserId);
		attributeGetterFunctions.put("userName", Student::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Student, String>)Student::setUserName);
		attributeGetterFunctions.put("createDate", Student::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Student, Date>)Student::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Student::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Student, Date>)Student::setModifiedDate);
		attributeGetterFunctions.put("groupId", Student::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Student, Long>)Student::setGroupId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getStudentId() {
		return _studentId;
	}

	@Override
	public void setStudentId(long studentId) {
		_studentId = studentId;
	}

	@JSON
	@Override
	public String getStudentName() {
		if (_studentName == null) {
			return "";
		}
		else {
			return _studentName;
		}
	}

	@Override
	public void setStudentName(String studentName) {
		_columnBitmask = -1L;

		if (_originalStudentName == null) {
			_originalStudentName = _studentName;
		}

		_studentName = studentName;
	}

	public String getOriginalStudentName() {
		return GetterUtil.getString(_originalStudentName);
	}

	@JSON
	@Override
	public String getStudentNickName() {
		if (_studentNickName == null) {
			return "";
		}
		else {
			return _studentNickName;
		}
	}

	@Override
	public void setStudentNickName(String studentNickName) {
		_studentNickName = studentNickName;
	}

	@JSON
	@Override
	public long getStudentMobNo() {
		return _studentMobNo;
	}

	@Override
	public void setStudentMobNo(long studentMobNo) {
		_columnBitmask |= STUDENTMOBNO_COLUMN_BITMASK;

		if (!_setOriginalStudentMobNo) {
			_setOriginalStudentMobNo = true;

			_originalStudentMobNo = _studentMobNo;
		}

		_studentMobNo = studentMobNo;
	}

	public long getOriginalStudentMobNo() {
		return _originalStudentMobNo;
	}

	@JSON
	@Override
	public boolean getStudentGender() {
		return _studentGender;
	}

	@JSON
	@Override
	public boolean isStudentGender() {
		return _studentGender;
	}

	@Override
	public void setStudentGender(boolean studentGender) {
		_studentGender = studentGender;
	}

	@JSON
	@Override
	public int getStudentAge() {
		return _studentAge;
	}

	@Override
	public void setStudentAge(int studentAge) {
		_studentAge = studentAge;
	}

	@JSON
	@Override
	public Date getStudentDOB() {
		return _studentDOB;
	}

	@Override
	public void setStudentDOB(Date studentDOB) {
		_studentDOB = studentDOB;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Student.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Student toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Student>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		StudentImpl studentImpl = new StudentImpl();

		studentImpl.setStudentId(getStudentId());
		studentImpl.setStudentName(getStudentName());
		studentImpl.setStudentNickName(getStudentNickName());
		studentImpl.setStudentMobNo(getStudentMobNo());
		studentImpl.setStudentGender(isStudentGender());
		studentImpl.setStudentAge(getStudentAge());
		studentImpl.setStudentDOB(getStudentDOB());
		studentImpl.setCompanyId(getCompanyId());
		studentImpl.setUserId(getUserId());
		studentImpl.setUserName(getUserName());
		studentImpl.setCreateDate(getCreateDate());
		studentImpl.setModifiedDate(getModifiedDate());
		studentImpl.setGroupId(getGroupId());

		studentImpl.resetOriginalValues();

		return studentImpl;
	}

	@Override
	public int compareTo(Student student) {
		int value = 0;

		value = getStudentName().compareTo(student.getStudentName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Student)) {
			return false;
		}

		Student student = (Student)obj;

		long primaryKey = student.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		StudentModelImpl studentModelImpl = this;

		studentModelImpl._originalStudentName = studentModelImpl._studentName;

		studentModelImpl._originalStudentMobNo = studentModelImpl._studentMobNo;

		studentModelImpl._setOriginalStudentMobNo = false;

		studentModelImpl._setModifiedDate = false;

		studentModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Student> toCacheModel() {
		StudentCacheModel studentCacheModel = new StudentCacheModel();

		studentCacheModel.studentId = getStudentId();

		studentCacheModel.studentName = getStudentName();

		String studentName = studentCacheModel.studentName;

		if ((studentName != null) && (studentName.length() == 0)) {
			studentCacheModel.studentName = null;
		}

		studentCacheModel.studentNickName = getStudentNickName();

		String studentNickName = studentCacheModel.studentNickName;

		if ((studentNickName != null) && (studentNickName.length() == 0)) {
			studentCacheModel.studentNickName = null;
		}

		studentCacheModel.studentMobNo = getStudentMobNo();

		studentCacheModel.studentGender = isStudentGender();

		studentCacheModel.studentAge = getStudentAge();

		Date studentDOB = getStudentDOB();

		if (studentDOB != null) {
			studentCacheModel.studentDOB = studentDOB.getTime();
		}
		else {
			studentCacheModel.studentDOB = Long.MIN_VALUE;
		}

		studentCacheModel.companyId = getCompanyId();

		studentCacheModel.userId = getUserId();

		studentCacheModel.userName = getUserName();

		String userName = studentCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			studentCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			studentCacheModel.createDate = createDate.getTime();
		}
		else {
			studentCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			studentCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			studentCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		studentCacheModel.groupId = getGroupId();

		return studentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Student, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Student, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Student, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Student)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Student, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Student, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Student, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Student)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Student>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _studentId;
	private String _studentName;
	private String _originalStudentName;
	private String _studentNickName;
	private long _studentMobNo;
	private long _originalStudentMobNo;
	private boolean _setOriginalStudentMobNo;
	private boolean _studentGender;
	private int _studentAge;
	private Date _studentDOB;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _groupId;
	private long _columnBitmask;
	private Student _escapedModel;

}