/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.takenaka.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import com.takenaka.model.DesignChangeDetails;
import com.takenaka.service.DesignChangeDetailsService;
import com.takenaka.service.persistence.DesignChangeDetailsPersistence;
import com.takenaka.service.persistence.ProjTablePersistence;
import com.takenaka.service.persistence.TriggerMeetingDetailsPersistence;
import com.takenaka.service.persistence.TriggerMeetingPersistence;
import com.takenaka.service.persistence.projgaiyoPersistence;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the design change details remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.takenaka.service.impl.DesignChangeDetailsServiceImpl}.
 * </p>
 *
 * @author Sanjay.Panchal
 * @see com.takenaka.service.impl.DesignChangeDetailsServiceImpl
 * @generated
 */
public abstract class DesignChangeDetailsServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, DesignChangeDetailsService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>DesignChangeDetailsService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.takenaka.service.DesignChangeDetailsServiceUtil</code>.
	 */
	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			DesignChangeDetailsService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		designChangeDetailsService = (DesignChangeDetailsService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return DesignChangeDetailsService.class.getName();
	}

	protected Class<?> getModelClass() {
		return DesignChangeDetails.class;
	}

	protected String getModelClassName() {
		return DesignChangeDetails.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				designChangeDetailsPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected com.takenaka.service.DesignChangeDetailsLocalService
		designChangeDetailsLocalService;

	protected DesignChangeDetailsService designChangeDetailsService;

	@Reference
	protected DesignChangeDetailsPersistence designChangeDetailsPersistence;

	@Reference
	protected projgaiyoPersistence projgaiyoPersistence;

	@Reference
	protected ProjTablePersistence projTablePersistence;

	@Reference
	protected TriggerMeetingPersistence triggerMeetingPersistence;

	@Reference
	protected TriggerMeetingDetailsPersistence triggerMeetingDetailsPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

}