/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.takenaka.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.takenaka.model.DesignChangeDetails;
import com.takenaka.service.DesignChangeDetailsLocalService;
import com.takenaka.service.persistence.DesignChangeDetailsPersistence;
import com.takenaka.service.persistence.ProjTablePersistence;
import com.takenaka.service.persistence.TriggerMeetingDetailsPersistence;
import com.takenaka.service.persistence.TriggerMeetingPersistence;
import com.takenaka.service.persistence.projgaiyoPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the design change details local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.takenaka.service.impl.DesignChangeDetailsLocalServiceImpl}.
 * </p>
 *
 * @author Sanjay.Panchal
 * @see com.takenaka.service.impl.DesignChangeDetailsLocalServiceImpl
 * @generated
 */
public abstract class DesignChangeDetailsLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, DesignChangeDetailsLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>DesignChangeDetailsLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.takenaka.service.DesignChangeDetailsLocalServiceUtil</code>.
	 */

	/**
	 * Adds the design change details to the database. Also notifies the appropriate model listeners.
	 *
	 * @param designChangeDetails the design change details
	 * @return the design change details that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DesignChangeDetails addDesignChangeDetails(
		DesignChangeDetails designChangeDetails) {

		designChangeDetails.setNew(true);

		return designChangeDetailsPersistence.update(designChangeDetails);
	}

	/**
	 * Creates a new design change details with the primary key. Does not add the design change details to the database.
	 *
	 * @param dcrChangeSeqno the primary key for the new design change details
	 * @return the new design change details
	 */
	@Override
	@Transactional(enabled = false)
	public DesignChangeDetails createDesignChangeDetails(long dcrChangeSeqno) {
		return designChangeDetailsPersistence.create(dcrChangeSeqno);
	}

	/**
	 * Deletes the design change details with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param dcrChangeSeqno the primary key of the design change details
	 * @return the design change details that was removed
	 * @throws PortalException if a design change details with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DesignChangeDetails deleteDesignChangeDetails(long dcrChangeSeqno)
		throws PortalException {

		return designChangeDetailsPersistence.remove(dcrChangeSeqno);
	}

	/**
	 * Deletes the design change details from the database. Also notifies the appropriate model listeners.
	 *
	 * @param designChangeDetails the design change details
	 * @return the design change details that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DesignChangeDetails deleteDesignChangeDetails(
		DesignChangeDetails designChangeDetails) {

		return designChangeDetailsPersistence.remove(designChangeDetails);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			DesignChangeDetails.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return designChangeDetailsPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.takenaka.model.impl.DesignChangeDetailsModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return designChangeDetailsPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.takenaka.model.impl.DesignChangeDetailsModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return designChangeDetailsPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return designChangeDetailsPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return designChangeDetailsPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public DesignChangeDetails fetchDesignChangeDetails(long dcrChangeSeqno) {
		return designChangeDetailsPersistence.fetchByPrimaryKey(dcrChangeSeqno);
	}

	/**
	 * Returns the design change details with the primary key.
	 *
	 * @param dcrChangeSeqno the primary key of the design change details
	 * @return the design change details
	 * @throws PortalException if a design change details with the primary key could not be found
	 */
	@Override
	public DesignChangeDetails getDesignChangeDetails(long dcrChangeSeqno)
		throws PortalException {

		return designChangeDetailsPersistence.findByPrimaryKey(dcrChangeSeqno);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			designChangeDetailsLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DesignChangeDetails.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("dcrChangeSeqno");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			designChangeDetailsLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			DesignChangeDetails.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"dcrChangeSeqno");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			designChangeDetailsLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DesignChangeDetails.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("dcrChangeSeqno");
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return designChangeDetailsPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return designChangeDetailsLocalService.deleteDesignChangeDetails(
			(DesignChangeDetails)persistedModel);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return designChangeDetailsPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the design change detailses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.takenaka.model.impl.DesignChangeDetailsModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of design change detailses
	 * @param end the upper bound of the range of design change detailses (not inclusive)
	 * @return the range of design change detailses
	 */
	@Override
	public List<DesignChangeDetails> getDesignChangeDetailses(
		int start, int end) {

		return designChangeDetailsPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of design change detailses.
	 *
	 * @return the number of design change detailses
	 */
	@Override
	public int getDesignChangeDetailsesCount() {
		return designChangeDetailsPersistence.countAll();
	}

	/**
	 * Updates the design change details in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param designChangeDetails the design change details
	 * @return the design change details that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DesignChangeDetails updateDesignChangeDetails(
		DesignChangeDetails designChangeDetails) {

		return designChangeDetailsPersistence.update(designChangeDetails);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			DesignChangeDetailsLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		designChangeDetailsLocalService =
			(DesignChangeDetailsLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return DesignChangeDetailsLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return DesignChangeDetails.class;
	}

	protected String getModelClassName() {
		return DesignChangeDetails.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				designChangeDetailsPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected DesignChangeDetailsLocalService designChangeDetailsLocalService;

	@Reference
	protected DesignChangeDetailsPersistence designChangeDetailsPersistence;

	@Reference
	protected projgaiyoPersistence projgaiyoPersistence;

	@Reference
	protected ProjTablePersistence projTablePersistence;

	@Reference
	protected TriggerMeetingPersistence triggerMeetingPersistence;

	@Reference
	protected TriggerMeetingDetailsPersistence triggerMeetingDetailsPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}