/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.takenaka.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.takenaka.model.projgaiyo;
import com.takenaka.service.persistence.DesignChangeDetailsPersistence;
import com.takenaka.service.persistence.ProjTablePersistence;
import com.takenaka.service.persistence.TriggerMeetingDetailsPersistence;
import com.takenaka.service.persistence.TriggerMeetingPersistence;
import com.takenaka.service.persistence.projgaiyoPersistence;
import com.takenaka.service.projgaiyoLocalService;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the projgaiyo local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.takenaka.service.impl.projgaiyoLocalServiceImpl}.
 * </p>
 *
 * @author Sanjay.Panchal
 * @see com.takenaka.service.impl.projgaiyoLocalServiceImpl
 * @generated
 */
public abstract class projgaiyoLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, projgaiyoLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>projgaiyoLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.takenaka.service.projgaiyoLocalServiceUtil</code>.
	 */

	/**
	 * Adds the projgaiyo to the database. Also notifies the appropriate model listeners.
	 *
	 * @param projgaiyo the projgaiyo
	 * @return the projgaiyo that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public projgaiyo addprojgaiyo(projgaiyo projgaiyo) {
		projgaiyo.setNew(true);

		return projgaiyoPersistence.update(projgaiyo);
	}

	/**
	 * Creates a new projgaiyo with the primary key. Does not add the projgaiyo to the database.
	 *
	 * @param groupId the primary key for the new projgaiyo
	 * @return the new projgaiyo
	 */
	@Override
	@Transactional(enabled = false)
	public projgaiyo createprojgaiyo(long groupId) {
		return projgaiyoPersistence.create(groupId);
	}

	/**
	 * Deletes the projgaiyo with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param groupId the primary key of the projgaiyo
	 * @return the projgaiyo that was removed
	 * @throws PortalException if a projgaiyo with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public projgaiyo deleteprojgaiyo(long groupId) throws PortalException {
		return projgaiyoPersistence.remove(groupId);
	}

	/**
	 * Deletes the projgaiyo from the database. Also notifies the appropriate model listeners.
	 *
	 * @param projgaiyo the projgaiyo
	 * @return the projgaiyo that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public projgaiyo deleteprojgaiyo(projgaiyo projgaiyo) {
		return projgaiyoPersistence.remove(projgaiyo);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			projgaiyo.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return projgaiyoPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.takenaka.model.impl.projgaiyoModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return projgaiyoPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.takenaka.model.impl.projgaiyoModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return projgaiyoPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return projgaiyoPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return projgaiyoPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public projgaiyo fetchprojgaiyo(long groupId) {
		return projgaiyoPersistence.fetchByPrimaryKey(groupId);
	}

	/**
	 * Returns the projgaiyo matching the UUID and group.
	 *
	 * @param uuid the projgaiyo's UUID
	 * @param groupId the primary key of the group
	 * @return the matching projgaiyo, or <code>null</code> if a matching projgaiyo could not be found
	 */
	@Override
	public projgaiyo fetchprojgaiyoByUuidAndGroupId(String uuid, long groupId) {
		return projgaiyoPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the projgaiyo with the primary key.
	 *
	 * @param groupId the primary key of the projgaiyo
	 * @return the projgaiyo
	 * @throws PortalException if a projgaiyo with the primary key could not be found
	 */
	@Override
	public projgaiyo getprojgaiyo(long groupId) throws PortalException {
		return projgaiyoPersistence.findByPrimaryKey(groupId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(projgaiyoLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(projgaiyo.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("groupId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			projgaiyoLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(projgaiyo.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("groupId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(projgaiyoLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(projgaiyo.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("groupId");
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return projgaiyoPersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return projgaiyoLocalService.deleteprojgaiyo((projgaiyo)persistedModel);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return projgaiyoPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns the projgaiyo matching the UUID and group.
	 *
	 * @param uuid the projgaiyo's UUID
	 * @param groupId the primary key of the group
	 * @return the matching projgaiyo
	 * @throws PortalException if a matching projgaiyo could not be found
	 */
	@Override
	public projgaiyo getprojgaiyoByUuidAndGroupId(String uuid, long groupId)
		throws PortalException {

		return projgaiyoPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the projgaiyos.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.takenaka.model.impl.projgaiyoModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of projgaiyos
	 * @param end the upper bound of the range of projgaiyos (not inclusive)
	 * @return the range of projgaiyos
	 */
	@Override
	public List<projgaiyo> getprojgaiyos(int start, int end) {
		return projgaiyoPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of projgaiyos.
	 *
	 * @return the number of projgaiyos
	 */
	@Override
	public int getprojgaiyosCount() {
		return projgaiyoPersistence.countAll();
	}

	/**
	 * Updates the projgaiyo in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param projgaiyo the projgaiyo
	 * @return the projgaiyo that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public projgaiyo updateprojgaiyo(projgaiyo projgaiyo) {
		return projgaiyoPersistence.update(projgaiyo);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			projgaiyoLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		projgaiyoLocalService = (projgaiyoLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return projgaiyoLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return projgaiyo.class;
	}

	protected String getModelClassName() {
		return projgaiyo.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = projgaiyoPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected DesignChangeDetailsPersistence designChangeDetailsPersistence;

	protected projgaiyoLocalService projgaiyoLocalService;

	@Reference
	protected projgaiyoPersistence projgaiyoPersistence;

	@Reference
	protected ProjTablePersistence projTablePersistence;

	@Reference
	protected TriggerMeetingPersistence triggerMeetingPersistence;

	@Reference
	protected TriggerMeetingDetailsPersistence triggerMeetingDetailsPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}