/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.takenaka.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DesignChangeDetails service. Represents a row in the &quot;DESIGN_CHANGE_DETAILS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.takenaka.model.impl.DesignChangeDetailsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.takenaka.model.impl.DesignChangeDetailsImpl</code>.
 * </p>
 *
 * @author Sanjay.Panchal
 * @see DesignChangeDetails
 * @generated
 */
@ProviderType
public interface DesignChangeDetailsModel
	extends BaseModel<DesignChangeDetails> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a design change details model instance should use the {@link DesignChangeDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this design change details.
	 *
	 * @return the primary key of this design change details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this design change details.
	 *
	 * @param primaryKey the primary key of this design change details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dcr change seqno of this design change details.
	 *
	 * @return the dcr change seqno of this design change details
	 */
	public long getDcrChangeSeqno();

	/**
	 * Sets the dcr change seqno of this design change details.
	 *
	 * @param dcrChangeSeqno the dcr change seqno of this design change details
	 */
	public void setDcrChangeSeqno(long dcrChangeSeqno);

	/**
	 * Returns the designchange subseqno of this design change details.
	 *
	 * @return the designchange subseqno of this design change details
	 */
	public long getDesignchangeSubseqno();

	/**
	 * Sets the designchange subseqno of this design change details.
	 *
	 * @param designchangeSubseqno the designchange subseqno of this design change details
	 */
	public void setDesignchangeSubseqno(long designchangeSubseqno);

	/**
	 * Returns the group ID of this design change details.
	 *
	 * @return the group ID of this design change details
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this design change details.
	 *
	 * @param groupId the group ID of this design change details
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the revision no of this design change details.
	 *
	 * @return the revision no of this design change details
	 */
	public int getRevisionNo();

	/**
	 * Sets the revision no of this design change details.
	 *
	 * @param revisionNo the revision no of this design change details
	 */
	public void setRevisionNo(int revisionNo);

	/**
	 * Returns the meeting ID of this design change details.
	 *
	 * @return the meeting ID of this design change details
	 */
	@AutoEscape
	public String getMeetingId();

	/**
	 * Sets the meeting ID of this design change details.
	 *
	 * @param meetingId the meeting ID of this design change details
	 */
	public void setMeetingId(String meetingId);

	/**
	 * Returns the issuer of this design change details.
	 *
	 * @return the issuer of this design change details
	 */
	@AutoEscape
	public String getIssuer();

	/**
	 * Sets the issuer of this design change details.
	 *
	 * @param issuer the issuer of this design change details
	 */
	public void setIssuer(String issuer);

	/**
	 * Returns the change type of this design change details.
	 *
	 * @return the change type of this design change details
	 */
	@AutoEscape
	public String getChangeType();

	/**
	 * Sets the change type of this design change details.
	 *
	 * @param changeType the change type of this design change details
	 */
	public void setChangeType(String changeType);

	/**
	 * Returns the change requestby of this design change details.
	 *
	 * @return the change requestby of this design change details
	 */
	@AutoEscape
	public String getChangeRequestby();

	/**
	 * Sets the change requestby of this design change details.
	 *
	 * @param changeRequestby the change requestby of this design change details
	 */
	public void setChangeRequestby(String changeRequestby);

	/**
	 * Returns the rfc ID of this design change details.
	 *
	 * @return the rfc ID of this design change details
	 */
	@AutoEscape
	public String getRfcId();

	/**
	 * Sets the rfc ID of this design change details.
	 *
	 * @param rfcId the rfc ID of this design change details
	 */
	public void setRfcId(String rfcId);

	/**
	 * Returns the rfc others of this design change details.
	 *
	 * @return the rfc others of this design change details
	 */
	@AutoEscape
	public String getRfcOthers();

	/**
	 * Sets the rfc others of this design change details.
	 *
	 * @param rfcOthers the rfc others of this design change details
	 */
	public void setRfcOthers(String rfcOthers);

	/**
	 * Returns the range of disclosure of this design change details.
	 *
	 * @return the range of disclosure of this design change details
	 */
	@AutoEscape
	public String getRangeOfDisclosure();

	/**
	 * Sets the range of disclosure of this design change details.
	 *
	 * @param rangeOfDisclosure the range of disclosure of this design change details
	 */
	public void setRangeOfDisclosure(String rangeOfDisclosure);

	/**
	 * Returns the floor of this design change details.
	 *
	 * @return the floor of this design change details
	 */
	@AutoEscape
	public String getFloor();

	/**
	 * Sets the floor of this design change details.
	 *
	 * @param floor the floor of this design change details
	 */
	public void setFloor(String floor);

	/**
	 * Returns the item of this design change details.
	 *
	 * @return the item of this design change details
	 */
	@AutoEscape
	public String getItem();

	/**
	 * Sets the item of this design change details.
	 *
	 * @param item the item of this design change details
	 */
	public void setItem(String item);

	/**
	 * Returns the originaldesgin detail of this design change details.
	 *
	 * @return the originaldesgin detail of this design change details
	 */
	@AutoEscape
	public String getOriginaldesginDetail();

	/**
	 * Sets the originaldesgin detail of this design change details.
	 *
	 * @param originaldesginDetail the originaldesgin detail of this design change details
	 */
	public void setOriginaldesginDetail(String originaldesginDetail);

	/**
	 * Returns the change detail of this design change details.
	 *
	 * @return the change detail of this design change details
	 */
	@AutoEscape
	public String getChangeDetail();

	/**
	 * Sets the change detail of this design change details.
	 *
	 * @param changeDetail the change detail of this design change details
	 */
	public void setChangeDetail(String changeDetail);

	/**
	 * Returns the action of this design change details.
	 *
	 * @return the action of this design change details
	 */
	@AutoEscape
	public String getAction();

	/**
	 * Sets the action of this design change details.
	 *
	 * @param action the action of this design change details
	 */
	public void setAction(String action);

	/**
	 * Returns the estdesign costtype of this design change details.
	 *
	 * @return the estdesign costtype of this design change details
	 */
	@AutoEscape
	public String getEstdesignCosttype();

	/**
	 * Sets the estdesign costtype of this design change details.
	 *
	 * @param estdesignCosttype the estdesign costtype of this design change details
	 */
	public void setEstdesignCosttype(String estdesignCosttype);

	/**
	 * Returns the estdesign cost of this design change details.
	 *
	 * @return the estdesign cost of this design change details
	 */
	public long getEstdesignCost();

	/**
	 * Sets the estdesign cost of this design change details.
	 *
	 * @param estdesignCost the estdesign cost of this design change details
	 */
	public void setEstdesignCost(long estdesignCost);

	/**
	 * Returns the estconstruction costtype of this design change details.
	 *
	 * @return the estconstruction costtype of this design change details
	 */
	@AutoEscape
	public String getEstconstructionCosttype();

	/**
	 * Sets the estconstruction costtype of this design change details.
	 *
	 * @param estconstructionCosttype the estconstruction costtype of this design change details
	 */
	public void setEstconstructionCosttype(String estconstructionCosttype);

	/**
	 * Returns the estconstruction cost of this design change details.
	 *
	 * @return the estconstruction cost of this design change details
	 */
	public long getEstconstructionCost();

	/**
	 * Sets the estconstruction cost of this design change details.
	 *
	 * @param estconstructionCost the estconstruction cost of this design change details
	 */
	public void setEstconstructionCost(long estconstructionCost);

	/**
	 * Returns the expense ajustment division of this design change details.
	 *
	 * @return the expense ajustment division of this design change details
	 */
	@AutoEscape
	public String getExpenseAjustmentDivision();

	/**
	 * Sets the expense ajustment division of this design change details.
	 *
	 * @param expenseAjustmentDivision the expense ajustment division of this design change details
	 */
	public void setExpenseAjustmentDivision(String expenseAjustmentDivision);

	/**
	 * Returns the attachment id1 of this design change details.
	 *
	 * @return the attachment id1 of this design change details
	 */
	public long getAttachmentId1();

	/**
	 * Sets the attachment id1 of this design change details.
	 *
	 * @param attachmentId1 the attachment id1 of this design change details
	 */
	public void setAttachmentId1(long attachmentId1);

	/**
	 * Returns the attachment id2 of this design change details.
	 *
	 * @return the attachment id2 of this design change details
	 */
	public long getAttachmentId2();

	/**
	 * Sets the attachment id2 of this design change details.
	 *
	 * @param attachmentId2 the attachment id2 of this design change details
	 */
	public void setAttachmentId2(long attachmentId2);

	/**
	 * Returns the attachment id3 of this design change details.
	 *
	 * @return the attachment id3 of this design change details
	 */
	public long getAttachmentId3();

	/**
	 * Sets the attachment id3 of this design change details.
	 *
	 * @param attachmentId3 the attachment id3 of this design change details
	 */
	public void setAttachmentId3(long attachmentId3);

	/**
	 * Returns the attachment id4 of this design change details.
	 *
	 * @return the attachment id4 of this design change details
	 */
	public long getAttachmentId4();

	/**
	 * Sets the attachment id4 of this design change details.
	 *
	 * @param attachmentId4 the attachment id4 of this design change details
	 */
	public void setAttachmentId4(long attachmentId4);

	/**
	 * Returns the attachment1 of this design change details.
	 *
	 * @return the attachment1 of this design change details
	 */
	@AutoEscape
	public String getAttachment1();

	/**
	 * Sets the attachment1 of this design change details.
	 *
	 * @param attachment1 the attachment1 of this design change details
	 */
	public void setAttachment1(String attachment1);

	/**
	 * Returns the attachment2 of this design change details.
	 *
	 * @return the attachment2 of this design change details
	 */
	@AutoEscape
	public String getAttachment2();

	/**
	 * Sets the attachment2 of this design change details.
	 *
	 * @param attachment2 the attachment2 of this design change details
	 */
	public void setAttachment2(String attachment2);

	/**
	 * Returns the attachment3 of this design change details.
	 *
	 * @return the attachment3 of this design change details
	 */
	@AutoEscape
	public String getAttachment3();

	/**
	 * Sets the attachment3 of this design change details.
	 *
	 * @param attachment3 the attachment3 of this design change details
	 */
	public void setAttachment3(String attachment3);

	/**
	 * Returns the attachment4 of this design change details.
	 *
	 * @return the attachment4 of this design change details
	 */
	@AutoEscape
	public String getAttachment4();

	/**
	 * Sets the attachment4 of this design change details.
	 *
	 * @param attachment4 the attachment4 of this design change details
	 */
	public void setAttachment4(String attachment4);

	/**
	 * Returns the response period of this design change details.
	 *
	 * @return the response period of this design change details
	 */
	@AutoEscape
	public String getResponsePeriod();

	/**
	 * Sets the response period of this design change details.
	 *
	 * @param responsePeriod the response period of this design change details
	 */
	public void setResponsePeriod(String responsePeriod);

	/**
	 * Returns the person in charge of this design change details.
	 *
	 * @return the person in charge of this design change details
	 */
	@AutoEscape
	public String getPersonInCharge();

	/**
	 * Sets the person in charge of this design change details.
	 *
	 * @param personInCharge the person in charge of this design change details
	 */
	public void setPersonInCharge(String personInCharge);

	/**
	 * Returns the approval no of this design change details.
	 *
	 * @return the approval no of this design change details
	 */
	public long getApprovalNo();

	/**
	 * Sets the approval no of this design change details.
	 *
	 * @param approvalNo the approval no of this design change details
	 */
	public void setApprovalNo(long approvalNo);

	/**
	 * Returns the approval status of this design change details.
	 *
	 * @return the approval status of this design change details
	 */
	@AutoEscape
	public String getApprovalStatus();

	/**
	 * Sets the approval status of this design change details.
	 *
	 * @param approvalStatus the approval status of this design change details
	 */
	public void setApprovalStatus(String approvalStatus);

	/**
	 * Returns the approval date of this design change details.
	 *
	 * @return the approval date of this design change details
	 */
	public Date getApprovalDate();

	/**
	 * Sets the approval date of this design change details.
	 *
	 * @param approvalDate the approval date of this design change details
	 */
	public void setApprovalDate(Date approvalDate);

	/**
	 * Returns the client approval status of this design change details.
	 *
	 * @return the client approval status of this design change details
	 */
	@AutoEscape
	public String getClientApprovalStatus();

	/**
	 * Sets the client approval status of this design change details.
	 *
	 * @param clientApprovalStatus the client approval status of this design change details
	 */
	public void setClientApprovalStatus(String clientApprovalStatus);

	/**
	 * Returns the client approval date of this design change details.
	 *
	 * @return the client approval date of this design change details
	 */
	public Date getClientApprovalDate();

	/**
	 * Sets the client approval date of this design change details.
	 *
	 * @param clientApprovalDate the client approval date of this design change details
	 */
	public void setClientApprovalDate(Date clientApprovalDate);

	/**
	 * Returns the construction status of this design change details.
	 *
	 * @return the construction status of this design change details
	 */
	@AutoEscape
	public String getConstructionStatus();

	/**
	 * Sets the construction status of this design change details.
	 *
	 * @param constructionStatus the construction status of this design change details
	 */
	public void setConstructionStatus(String constructionStatus);

	/**
	 * Returns the construction date of this design change details.
	 *
	 * @return the construction date of this design change details
	 */
	public Date getConstructionDate();

	/**
	 * Sets the construction date of this design change details.
	 *
	 * @param constructionDate the construction date of this design change details
	 */
	public void setConstructionDate(Date constructionDate);

	/**
	 * Returns the created by of this design change details.
	 *
	 * @return the created by of this design change details
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this design change details.
	 *
	 * @param createdBy the created by of this design change details
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the created on of this design change details.
	 *
	 * @return the created on of this design change details
	 */
	public Date getCreatedOn();

	/**
	 * Sets the created on of this design change details.
	 *
	 * @param createdOn the created on of this design change details
	 */
	public void setCreatedOn(Date createdOn);

	/**
	 * Returns the modified by of this design change details.
	 *
	 * @return the modified by of this design change details
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this design change details.
	 *
	 * @param modifiedBy the modified by of this design change details
	 */
	public void setModifiedBy(String modifiedBy);

	/**
	 * Returns the modified on of this design change details.
	 *
	 * @return the modified on of this design change details
	 */
	public Date getModifiedOn();

	/**
	 * Sets the modified on of this design change details.
	 *
	 * @param modifiedOn the modified on of this design change details
	 */
	public void setModifiedOn(Date modifiedOn);

	/**
	 * Returns the is active of this design change details.
	 *
	 * @return the is active of this design change details
	 */
	public boolean getIsActive();

	/**
	 * Returns <code>true</code> if this design change details is is active.
	 *
	 * @return <code>true</code> if this design change details is is active; <code>false</code> otherwise
	 */
	public boolean isIsActive();

	/**
	 * Sets whether this design change details is is active.
	 *
	 * @param isActive the is active of this design change details
	 */
	public void setIsActive(boolean isActive);

}