/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.takenaka.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProjTable service. Represents a row in the &quot;PROJTABLE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.takenaka.model.impl.ProjTableModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.takenaka.model.impl.ProjTableImpl</code>.
 * </p>
 *
 * @author Sanjay.Panchal
 * @see ProjTable
 * @generated
 */
@ProviderType
public interface ProjTableModel extends BaseModel<ProjTable> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a proj table model instance should use the {@link ProjTable} interface instead.
	 */

	/**
	 * Returns the primary key of this proj table.
	 *
	 * @return the primary key of this proj table
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this proj table.
	 *
	 * @param primaryKey the primary key of this proj table
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the rec ID of this proj table.
	 *
	 * @return the rec ID of this proj table
	 */
	public long getRecId();

	/**
	 * Sets the rec ID of this proj table.
	 *
	 * @param recId the rec ID of this proj table
	 */
	public void setRecId(long recId);

	/**
	 * Returns the group ID of this proj table.
	 *
	 * @return the group ID of this proj table
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this proj table.
	 *
	 * @param groupId the group ID of this proj table
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the group flag of this proj table.
	 *
	 * @return the group flag of this proj table
	 */
	@AutoEscape
	public String getGroupFlag();

	/**
	 * Sets the group flag of this proj table.
	 *
	 * @param groupFlag the group flag of this proj table
	 */
	public void setGroupFlag(String groupFlag);

	/**
	 * Returns the yoso koji cd of this proj table.
	 *
	 * @return the yoso koji cd of this proj table
	 */
	@AutoEscape
	public String getYosoKojiCd();

	/**
	 * Sets the yoso koji cd of this proj table.
	 *
	 * @param yosoKojiCd the yoso koji cd of this proj table
	 */
	public void setYosoKojiCd(String yosoKojiCd);

	/**
	 * Returns the sekkei cd of this proj table.
	 *
	 * @return the sekkei cd of this proj table
	 */
	@AutoEscape
	public String getSekkeiCd();

	/**
	 * Sets the sekkei cd of this proj table.
	 *
	 * @param sekkeiCd the sekkei cd of this proj table
	 */
	public void setSekkeiCd(String sekkeiCd);

	/**
	 * Returns the sekkei cd yy of this proj table.
	 *
	 * @return the sekkei cd yy of this proj table
	 */
	@AutoEscape
	public String getSekkeiCdYy();

	/**
	 * Sets the sekkei cd yy of this proj table.
	 *
	 * @param sekkeiCdYy the sekkei cd yy of this proj table
	 */
	public void setSekkeiCdYy(String sekkeiCdYy);

	/**
	 * Returns the mitumori nendo of this proj table.
	 *
	 * @return the mitumori nendo of this proj table
	 */
	@AutoEscape
	public String getMitumoriNendo();

	/**
	 * Sets the mitumori nendo of this proj table.
	 *
	 * @param mitumoriNendo the mitumori nendo of this proj table
	 */
	public void setMitumoriNendo(String mitumoriNendo);

	/**
	 * Returns the mitumori cd of this proj table.
	 *
	 * @return the mitumori cd of this proj table
	 */
	@AutoEscape
	public String getMitumoriCd();

	/**
	 * Sets the mitumori cd of this proj table.
	 *
	 * @param mitumoriCd the mitumori cd of this proj table
	 */
	public void setMitumoriCd(String mitumoriCd);

	/**
	 * Returns the koji cd of this proj table.
	 *
	 * @return the koji cd of this proj table
	 */
	@AutoEscape
	public String getKojiCd();

	/**
	 * Sets the koji cd of this proj table.
	 *
	 * @param kojiCd the koji cd of this proj table
	 */
	public void setKojiCd(String kojiCd);

	/**
	 * Returns the mitumori seiri no of this proj table.
	 *
	 * @return the mitumori seiri no of this proj table
	 */
	@AutoEscape
	public String getMitumoriSeiriNo();

	/**
	 * Sets the mitumori seiri no of this proj table.
	 *
	 * @param mitumoriSeiriNo the mitumori seiri no of this proj table
	 */
	public void setMitumoriSeiriNo(String mitumoriSeiriNo);

	/**
	 * Returns the shukan sekkei cd of this proj table.
	 *
	 * @return the shukan sekkei cd of this proj table
	 */
	@AutoEscape
	public String getShukanSekkeiCd();

	/**
	 * Sets the shukan sekkei cd of this proj table.
	 *
	 * @param shukanSekkeiCd the shukan sekkei cd of this proj table
	 */
	public void setShukanSekkeiCd(String shukanSekkeiCd);

	/**
	 * Returns the sekkei togo saki of this proj table.
	 *
	 * @return the sekkei togo saki of this proj table
	 */
	@AutoEscape
	public String getSekkeiTogoSaki();

	/**
	 * Sets the sekkei togo saki of this proj table.
	 *
	 * @param sekkeiTogoSaki the sekkei togo saki of this proj table
	 */
	public void setSekkeiTogoSaki(String sekkeiTogoSaki);

	/**
	 * Returns the sekkei bunkatu moto of this proj table.
	 *
	 * @return the sekkei bunkatu moto of this proj table
	 */
	@AutoEscape
	public String getSekkeiBunkatuMoto();

	/**
	 * Sets the sekkei bunkatu moto of this proj table.
	 *
	 * @param sekkeiBunkatuMoto the sekkei bunkatu moto of this proj table
	 */
	public void setSekkeiBunkatuMoto(String sekkeiBunkatuMoto);

	/**
	 * Returns the jutaku sekkei taisho of this proj table.
	 *
	 * @return the jutaku sekkei taisho of this proj table
	 */
	@AutoEscape
	public String getJutakuSekkeiTaisho();

	/**
	 * Sets the jutaku sekkei taisho of this proj table.
	 *
	 * @param jutakuSekkeiTaisho the jutaku sekkei taisho of this proj table
	 */
	public void setJutakuSekkeiTaisho(String jutakuSekkeiTaisho);

	/**
	 * Returns the honsiten rid of this proj table.
	 *
	 * @return the honsiten rid of this proj table
	 */
	@AutoEscape
	public String getHonsitenRid();

	/**
	 * Sets the honsiten rid of this proj table.
	 *
	 * @param honsitenRid the honsiten rid of this proj table
	 */
	public void setHonsitenRid(String honsitenRid);

	/**
	 * Returns the honsiten gid of this proj table.
	 *
	 * @return the honsiten gid of this proj table
	 */
	@AutoEscape
	public String getHonsitenGid();

	/**
	 * Sets the honsiten gid of this proj table.
	 *
	 * @param honsitenGid the honsiten gid of this proj table
	 */
	public void setHonsitenGid(String honsitenGid);

	/**
	 * Returns the org ykoji of this proj table.
	 *
	 * @return the org ykoji of this proj table
	 */
	@AutoEscape
	public String getOrgYkoji();

	/**
	 * Sets the org ykoji of this proj table.
	 *
	 * @param orgYkoji the org ykoji of this proj table
	 */
	public void setOrgYkoji(String orgYkoji);

	/**
	 * Returns the org jkoji of this proj table.
	 *
	 * @return the org jkoji of this proj table
	 */
	@AutoEscape
	public String getOrgJKOJI();

	/**
	 * Sets the org jkoji of this proj table.
	 *
	 * @param orgJKOJI the org jkoji of this proj table
	 */
	public void setOrgJKOJI(String orgJKOJI);

	/**
	 * Returns the org mdd of this proj table.
	 *
	 * @return the org mdd of this proj table
	 */
	@AutoEscape
	public String getOrgMdd();

	/**
	 * Sets the org mdd of this proj table.
	 *
	 * @param orgMdd the org mdd of this proj table
	 */
	public void setOrgMdd(String orgMdd);

	/**
	 * Returns the org pdd of this proj table.
	 *
	 * @return the org pdd of this proj table
	 */
	@AutoEscape
	public String getOrgPdd();

	/**
	 * Sets the org pdd of this proj table.
	 *
	 * @param orgPdd the org pdd of this proj table
	 */
	public void setOrgPdd(String orgPdd);

	/**
	 * Returns the org esmas of this proj table.
	 *
	 * @return the org esmas of this proj table
	 */
	@AutoEscape
	public String getOrgEsmas();

	/**
	 * Sets the org esmas of this proj table.
	 *
	 * @param orgEsmas the org esmas of this proj table
	 */
	public void setOrgEsmas(String orgEsmas);

	/**
	 * Returns the org prist of this proj table.
	 *
	 * @return the org prist of this proj table
	 */
	@AutoEscape
	public String getOrgPrist();

	/**
	 * Sets the org prist of this proj table.
	 *
	 * @param orgPrist the org prist of this proj table
	 */
	public void setOrgPrist(String orgPrist);

	/**
	 * Returns the proc sekkei of this proj table.
	 *
	 * @return the proc sekkei of this proj table
	 */
	@AutoEscape
	public String getProcSekkei();

	/**
	 * Sets the proc sekkei of this proj table.
	 *
	 * @param procSekkei the proc sekkei of this proj table
	 */
	public void setProcSekkei(String procSekkei);

	/**
	 * Returns the proc mitumori of this proj table.
	 *
	 * @return the proc mitumori of this proj table
	 */
	@AutoEscape
	public String getProcMitumori();

	/**
	 * Sets the proc mitumori of this proj table.
	 *
	 * @param procMitumori the proc mitumori of this proj table
	 */
	public void setProcMitumori(String procMitumori);

	/**
	 * Returns the proc sekkei oen of this proj table.
	 *
	 * @return the proc sekkei oen of this proj table
	 */
	@AutoEscape
	public String getProcSekkeiOen();

	/**
	 * Sets the proc sekkei oen of this proj table.
	 *
	 * @param procSekkeiOen the proc sekkei oen of this proj table
	 */
	public void setProcSekkeiOen(String procSekkeiOen);

	/**
	 * Returns the proc sekkei togo of this proj table.
	 *
	 * @return the proc sekkei togo of this proj table
	 */
	@AutoEscape
	public String getProcSekkeiTogo();

	/**
	 * Sets the proc sekkei togo of this proj table.
	 *
	 * @param procSekkeiTogo the proc sekkei togo of this proj table
	 */
	public void setProcSekkeiTogo(String procSekkeiTogo);

	/**
	 * Returns the proc sekkei bunkatu of this proj table.
	 *
	 * @return the proc sekkei bunkatu of this proj table
	 */
	@AutoEscape
	public String getProcSekkeiBunkatu();

	/**
	 * Sets the proc sekkei bunkatu of this proj table.
	 *
	 * @param procSekkeiBunkatu the proc sekkei bunkatu of this proj table
	 */
	public void setProcSekkeiBunkatu(String procSekkeiBunkatu);

	/**
	 * Returns the proc sekkei jutaku of this proj table.
	 *
	 * @return the proc sekkei jutaku of this proj table
	 */
	@AutoEscape
	public String getProcSekkeiJutaku();

	/**
	 * Sets the proc sekkei jutaku of this proj table.
	 *
	 * @param procSekkeiJutaku the proc sekkei jutaku of this proj table
	 */
	public void setProcSekkeiJutaku(String procSekkeiJutaku);

	/**
	 * Returns the taketu chusi toketu kb of this proj table.
	 *
	 * @return the taketu chusi toketu kb of this proj table
	 */
	@AutoEscape
	public String getTaketuChusiToketuKb();

	/**
	 * Sets the taketu chusi toketu kb of this proj table.
	 *
	 * @param taketuChusiToketuKb the taketu chusi toketu kb of this proj table
	 */
	public void setTaketuChusiToketuKb(String taketuChusiToketuKb);

	/**
	 * Returns the kanryo chusi status of this proj table.
	 *
	 * @return the kanryo chusi status of this proj table
	 */
	@AutoEscape
	public String getKanryoChusiStatus();

	/**
	 * Sets the kanryo chusi status of this proj table.
	 *
	 * @param kanryoChusiStatus the kanryo chusi status of this proj table
	 */
	public void setKanryoChusiStatus(String kanryoChusiStatus);

	/**
	 * Returns the mitumori keijo shubetu of this proj table.
	 *
	 * @return the mitumori keijo shubetu of this proj table
	 */
	@AutoEscape
	public String getMitumoriKeijoShubetu();

	/**
	 * Sets the mitumori keijo shubetu of this proj table.
	 *
	 * @param mitumoriKeijoShubetu the mitumori keijo shubetu of this proj table
	 */
	public void setMitumoriKeijoShubetu(String mitumoriKeijoShubetu);

	/**
	 * Returns the torikesi kb of this proj table.
	 *
	 * @return the torikesi kb of this proj table
	 */
	@AutoEscape
	public String getTorikesiKb();

	/**
	 * Sets the torikesi kb of this proj table.
	 *
	 * @param torikesiKb the torikesi kb of this proj table
	 */
	public void setTorikesiKb(String torikesiKb);

	/**
	 * Returns the kessan nendo of this proj table.
	 *
	 * @return the kessan nendo of this proj table
	 */
	@AutoEscape
	public String getKessanNendo();

	/**
	 * Sets the kessan nendo of this proj table.
	 *
	 * @param kessanNendo the kessan nendo of this proj table
	 */
	public void setKessanNendo(String kessanNendo);

	/**
	 * Returns the upd date of this proj table.
	 *
	 * @return the upd date of this proj table
	 */
	@AutoEscape
	public String getUpdDate();

	/**
	 * Sets the upd date of this proj table.
	 *
	 * @param updDate the upd date of this proj table
	 */
	public void setUpdDate(String updDate);

	/**
	 * Returns the upd time of this proj table.
	 *
	 * @return the upd time of this proj table
	 */
	@AutoEscape
	public String getUpdTime();

	/**
	 * Sets the upd time of this proj table.
	 *
	 * @param updTime the upd time of this proj table
	 */
	public void setUpdTime(String updTime);

}