/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.takenaka.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the projgaiyo service. Represents a row in the &quot;PROJGAIYO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.takenaka.model.impl.projgaiyoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.takenaka.model.impl.projgaiyoImpl</code>.
 * </p>
 *
 * @author Sanjay.Panchal
 * @see projgaiyo
 * @generated
 */
@ProviderType
public interface projgaiyoModel extends BaseModel<projgaiyo> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a projgaiyo model instance should use the {@link projgaiyo} interface instead.
	 */

	/**
	 * Returns the primary key of this projgaiyo.
	 *
	 * @return the primary key of this projgaiyo
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this projgaiyo.
	 *
	 * @param primaryKey the primary key of this projgaiyo
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this projgaiyo.
	 *
	 * @return the uuid of this projgaiyo
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this projgaiyo.
	 *
	 * @param uuid the uuid of this projgaiyo
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the group ID of this projgaiyo.
	 *
	 * @return the group ID of this projgaiyo
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this projgaiyo.
	 *
	 * @param groupId the group ID of this projgaiyo
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the proj nm of this projgaiyo.
	 *
	 * @return the proj nm of this projgaiyo
	 */
	@AutoEscape
	public String getProjNm();

	/**
	 * Sets the proj nm of this projgaiyo.
	 *
	 * @param projNm the proj nm of this projgaiyo
	 */
	public void setProjNm(String projNm);

	/**
	 * Returns the proj nm kana of this projgaiyo.
	 *
	 * @return the proj nm kana of this projgaiyo
	 */
	@AutoEscape
	public String getProjNmKana();

	/**
	 * Sets the proj nm kana of this projgaiyo.
	 *
	 * @param projNmKana the proj nm kana of this projgaiyo
	 */
	public void setProjNmKana(String projNmKana);

	/**
	 * Returns the kenchiku nusi cd of this projgaiyo.
	 *
	 * @return the kenchiku nusi cd of this projgaiyo
	 */
	@AutoEscape
	public String getKenchikuNusiCd();

	/**
	 * Sets the kenchiku nusi cd of this projgaiyo.
	 *
	 * @param kenchikuNusiCd the kenchiku nusi cd of this projgaiyo
	 */
	public void setKenchikuNusiCd(String kenchikuNusiCd);

	/**
	 * Returns the kenchiku nusi nm of this projgaiyo.
	 *
	 * @return the kenchiku nusi nm of this projgaiyo
	 */
	@AutoEscape
	public String getKenchikuNusiNm();

	/**
	 * Sets the kenchiku nusi nm of this projgaiyo.
	 *
	 * @param kenchikuNusiNm the kenchiku nusi nm of this projgaiyo
	 */
	public void setKenchikuNusiNm(String kenchikuNusiNm);

	/**
	 * Returns the kenchiku chi cd of this projgaiyo.
	 *
	 * @return the kenchiku chi cd of this projgaiyo
	 */
	@AutoEscape
	public String getKenchikuChiCd();

	/**
	 * Sets the kenchiku chi cd of this projgaiyo.
	 *
	 * @param kenchikuChiCd the kenchiku chi cd of this projgaiyo
	 */
	public void setKenchikuChiCd(String kenchikuChiCd);

	/**
	 * Returns the kenchiku chi nm of this projgaiyo.
	 *
	 * @return the kenchiku chi nm of this projgaiyo
	 */
	@AutoEscape
	public String getKenchikuChiNm();

	/**
	 * Sets the kenchiku chi nm of this projgaiyo.
	 *
	 * @param kenchikuChiNm the kenchiku chi nm of this projgaiyo
	 */
	public void setKenchikuChiNm(String kenchikuChiNm);

	/**
	 * Returns the tatemono yoto1 of this projgaiyo.
	 *
	 * @return the tatemono yoto1 of this projgaiyo
	 */
	@AutoEscape
	public String getTatemonoYoto1();

	/**
	 * Sets the tatemono yoto1 of this projgaiyo.
	 *
	 * @param tatemonoYoto1 the tatemono yoto1 of this projgaiyo
	 */
	public void setTatemonoYoto1(String tatemonoYoto1);

	/**
	 * Returns the tatemono yoto2 of this projgaiyo.
	 *
	 * @return the tatemono yoto2 of this projgaiyo
	 */
	@AutoEscape
	public String getTatemonoYoto2();

	/**
	 * Sets the tatemono yoto2 of this projgaiyo.
	 *
	 * @param tatemonoYoto2 the tatemono yoto2 of this projgaiyo
	 */
	public void setTatemonoYoto2(String tatemonoYoto2);

	/**
	 * Returns the tatemono yoto3 of this projgaiyo.
	 *
	 * @return the tatemono yoto3 of this projgaiyo
	 */
	@AutoEscape
	public String getTatemonoYoto3();

	/**
	 * Sets the tatemono yoto3 of this projgaiyo.
	 *
	 * @param tatemonoYoto3 the tatemono yoto3 of this projgaiyo
	 */
	public void setTatemonoYoto3(String tatemonoYoto3);

	/**
	 * Returns the kaisu b of this projgaiyo.
	 *
	 * @return the kaisu b of this projgaiyo
	 */
	public Double getKaisuB();

	/**
	 * Sets the kaisu b of this projgaiyo.
	 *
	 * @param kaisuB the kaisu b of this projgaiyo
	 */
	public void setKaisuB(Double kaisuB);

	/**
	 * Returns the kaisu f of this projgaiyo.
	 *
	 * @return the kaisu f of this projgaiyo
	 */
	public Double getKaisuF();

	/**
	 * Sets the kaisu f of this projgaiyo.
	 *
	 * @param kaisuF the kaisu f of this projgaiyo
	 */
	public void setKaisuF(Double kaisuF);

	/**
	 * Returns the kaisu p of this projgaiyo.
	 *
	 * @return the kaisu p of this projgaiyo
	 */
	public Double getKaisuP();

	/**
	 * Sets the kaisu p of this projgaiyo.
	 *
	 * @param kaisuP the kaisu p of this projgaiyo
	 */
	public void setKaisuP(Double kaisuP);

	/**
	 * Returns the kozo shubetu1 of this projgaiyo.
	 *
	 * @return the kozo shubetu1 of this projgaiyo
	 */
	@AutoEscape
	public String getKozoShubetu1();

	/**
	 * Sets the kozo shubetu1 of this projgaiyo.
	 *
	 * @param kozoShubetu1 the kozo shubetu1 of this projgaiyo
	 */
	public void setKozoShubetu1(String kozoShubetu1);

	/**
	 * Returns the kozo shubetu2 of this projgaiyo.
	 *
	 * @return the kozo shubetu2 of this projgaiyo
	 */
	@AutoEscape
	public String getKozoShubetu2();

	/**
	 * Sets the kozo shubetu2 of this projgaiyo.
	 *
	 * @param kozoShubetu2 the kozo shubetu2 of this projgaiyo
	 */
	public void setKozoShubetu2(String kozoShubetu2);

	/**
	 * Returns the kozo shubetu3 of this projgaiyo.
	 *
	 * @return the kozo shubetu3 of this projgaiyo
	 */
	@AutoEscape
	public String getKozoShubetu3();

	/**
	 * Sets the kozo shubetu3 of this projgaiyo.
	 *
	 * @param kozoShubetu3 the kozo shubetu3 of this projgaiyo
	 */
	public void setKozoShubetu3(String kozoShubetu3);

	/**
	 * Returns the nobeyuka menseki of this projgaiyo.
	 *
	 * @return the nobeyuka menseki of this projgaiyo
	 */
	public Double getNobeyukaMenseki();

	/**
	 * Sets the nobeyuka menseki of this projgaiyo.
	 *
	 * @param nobeyukaMenseki the nobeyuka menseki of this projgaiyo
	 */
	public void setNobeyukaMenseki(Double nobeyukaMenseki);

	/**
	 * Returns the kenchiku menseki of this projgaiyo.
	 *
	 * @return the kenchiku menseki of this projgaiyo
	 */
	public Double getKenchikuMenseki();

	/**
	 * Sets the kenchiku menseki of this projgaiyo.
	 *
	 * @param kenchikuMenseki the kenchiku menseki of this projgaiyo
	 */
	public void setKenchikuMenseki(Double kenchikuMenseki);

	/**
	 * Returns the chakko bi of this projgaiyo.
	 *
	 * @return the chakko bi of this projgaiyo
	 */
	@AutoEscape
	public String getChakkoBi();

	/**
	 * Sets the chakko bi of this projgaiyo.
	 *
	 * @param chakkoBi the chakko bi of this projgaiyo
	 */
	public void setChakkoBi(String chakkoBi);

	/**
	 * Returns the shunko bi of this projgaiyo.
	 *
	 * @return the shunko bi of this projgaiyo
	 */
	@AutoEscape
	public String getShunkoBi();

	/**
	 * Sets the shunko bi of this projgaiyo.
	 *
	 * @param shunkoBi the shunko bi of this projgaiyo
	 */
	public void setShunkoBi(String shunkoBi);

	/**
	 * Returns the sekkei kb of this projgaiyo.
	 *
	 * @return the sekkei kb of this projgaiyo
	 */
	@AutoEscape
	public String getSekkeiKb();

	/**
	 * Sets the sekkei kb of this projgaiyo.
	 *
	 * @param sekkeiKb the sekkei kb of this projgaiyo
	 */
	public void setSekkeiKb(String sekkeiKb);

	/**
	 * Returns the seko kb of this projgaiyo.
	 *
	 * @return the seko kb of this projgaiyo
	 */
	@AutoEscape
	public String getSekoKb();

	/**
	 * Sets the seko kb of this projgaiyo.
	 *
	 * @param sekoKb the seko kb of this projgaiyo
	 */
	public void setSekoKb(String sekoKb);

	/**
	 * Returns the sagyosho chiku of this projgaiyo.
	 *
	 * @return the sagyosho chiku of this projgaiyo
	 */
	@AutoEscape
	public String getSagyoshoChiku();

	/**
	 * Sets the sagyosho chiku of this projgaiyo.
	 *
	 * @param sagyoshoChiku the sagyosho chiku of this projgaiyo
	 */
	public void setSagyoshoChiku(String sagyoshoChiku);

	/**
	 * Returns the upd date of this projgaiyo.
	 *
	 * @return the upd date of this projgaiyo
	 */
	@AutoEscape
	public String getUpdDate();

	/**
	 * Sets the upd date of this projgaiyo.
	 *
	 * @param updDate the upd date of this projgaiyo
	 */
	public void setUpdDate(String updDate);

	/**
	 * Returns the upd time of this projgaiyo.
	 *
	 * @return the upd time of this projgaiyo
	 */
	@AutoEscape
	public String getUpdTime();

	/**
	 * Sets the upd time of this projgaiyo.
	 *
	 * @param updTime the upd time of this projgaiyo
	 */
	public void setUpdTime(String updTime);

}