create table STUDENT (
	STUDENTID LONG not null primary key,
	STUDENTNAME VARCHAR(75) null,
	STUDENTNICKNAME VARCHAR(75) null,
	STUDENTMOBNO LONG,
	STUDENTGENDER BOOLEAN,
	STUDENTAGE INTEGER,
	STUDENTDOB DATE null,
	COMPANYID LONG,
	USERID LONG,
	USERNAME VARCHAR(75) null,
	CREATEDATE DATE null,
	MODIFIEDDATE DATE null,
	GROUPID LONG
);